import Pkg

Pkg.add("Dates")
Pkg.add("Format")
Pkg.add("Getopt")
Pkg.add("MethodAnalysis")
Pkg.add("OffsetArrays")
Pkg.add("Permutations")
Pkg.add("Random")
Pkg.add("Distributions")
Pkg.add("SpecialFunctions")
Pkg.add("Unicode")
Pkg.add("LinearAlgebra")
Pkg.add("Statistics")
Pkg.add("Test")
Pkg.add("Plots")
Pkg.add("StatsPlots")
Pkg.add("DataFrames")
Pkg.add("CSV")
